# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.et.be-ips
url: https://www.earlytracks.com/standards/fhir/ips_be
canonical: https://www.earlytracks.com/standards/fhir/ips_be
name: hl7.fhir.et.ips
title: Belgian IPS
status: draft
description: Belgian IPS by EarlyTracks
date: 2024-02-18
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build

contact:
  - name: EarlyTracks Semantic Interoperability Service
    telecom:
      - system: email
        value: resources@earlytracks.com
        use: work

        

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  FHIR Artifacts: #artifact.html
      Profiles and Extensions: profiles-and-extensions.html
      Terminology: terminology.html
  Examples: examples.html


dependencies:
  hl7.fhir.us.core: latest
  hl7.fhir.be.core: latest
  hl7.fhir.be.core-clinical: latest
  hl7.fhir.uv.ips: latest
